os: osx
osx_image: xcode11
language: node_js
node_js: lts/*

env:
  - ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

addons:
  chrome: stable

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then yarn run electron:pack; fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist_gh_pages
    on:
      repo: dtom90/Produc-dev
      branch: master
